### ISSUE TITLE
【建议】可以适配python3.9吗

### ISSUE THREAD

**Issue by Agnes4m** [shinianj/nonebot_plugin_horserace#2]
如题

**Comment by shinianj** [comment]
我写的时候工作环境是3.10，使用是3.8以上都可以使用的

**Comment by Agnes4m** [comment]
但是不能pip（悲）
```
root@lsRvGzPA14:~# pip install --upgrade nonebot_plugin_horserace
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Ignored the following versions that require a different python version: 2.2 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement nonebot_plugin_horserace (from versions: none)
ERROR: No matching distribution found for nonebot_plugin_horserace
```

**Comment by shinianj** [comment]
还有这种事？那……要不先直接git下下去用用？

**Comment by Agnes4m** [comment]
读取事件显示是成功的，但输出的事件是空白。还有是这里限制了3.10
![image](https://user-images.githubusercontent.com/70925546/185797647-41afd9a2-5ee0-4f0f-ae77-d0ada036ee7f.png)

**Comment by shinianj** [comment]
> 读取事件显示是成功的，但输出的事件是空白。还有是这里限制了3.10 ![image](https://user-images.githubusercontent.com/70925546/185797647-41afd9a2-5ee0-4f0f-ae77-d0ada036ee7f.png)

输出空白的图片能看看吗，然后这里更改的话，pypi那边是不会改的，所以只能使用nb plugin
